### ISSUE TITLE
Error message: Annotation can be only constant variable...

### ISSUE THREAD

**Issue by psiphi75** [vadimtsushko/angular_objectory_demo#1]
I get the following error message in the Dart Editor:

```
Annotation can be only constant variable or constant constructor invocation
```

It appears in a few places.  One example is in main.dart for the following code:

```
@NgController(
    selector: '[recipe-book]',
    publishAs: 'ctrl')
```

I have just started using Dart and Angular, so I don't know how to proceed.  I see this package was last updated 6 months ago.  I presume it is out-of-date with the latest release of Dart, or I have done a noob mistake (although I have not changed a thing).

Version details are:
Dart Editor version 1.3.3.release (STABLE)
Dart SDK version 1.3.3
Ubuntu 14.04

**Comment by vadimtsushko** [comment]
You are right, sorry.
I believe demo should be rewritten based on current version of angular_demo, but I cannot promise that I'll do it soon. 
I'll try to update it as soon as I find the time

**Comment by Gastonite** [comment]
Hi,
upgrade to angulardart 0.10 is not so hard, just need replacing all 
"NgSomething" by "Something",
and the "Directives" becomes "Decorator", the "Filter" becomes 
"Formatter",

==>  https://github.com/angular/angular.dart/blob/master/CHANGELOG.md

;)

**Comment by vadimtsushko** [comment]
I made demo anew based on current version of angular.dart.tutorial Chapter 6. Works with angulart.dart 0.10.0

**Comment by psiphi75** [comment]
Thanks.  Works great now.
